services:

  mysql:
    image: mysql:8.0
    container_name: inventario-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: InventarioFerreteria
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql/master.cnf:/etc/mysql/conf.d/master.cnf:ro
    ports:
      - "3306:3306"
    networks:
      - inventario-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: "8080"
      DB_CONNECTION: "server=mysql;database=InventarioFerreteria;user=root;password=${MYSQL_ROOT_PASSWORD};"
      JWT_KEY: ${JWT_KEY}
    volumes:
      - dataprotection_keys:/app/DataProtection-Keys
    ports:
      - "5136:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventario-net

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - inventario-net

volumes:
  mysql_data:
  dataprotection_keys:

networks:
  inventario-net:
    driver: bridge
